name: pong-dqn
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pip:
      - gymnasium[atari]==1.2.0
      - ale-py==0.11.2
      - torch==2.8.0
      - numpy==2.3.5
      - matplotlib==3.10.8
      - scipy>=1.13,<2
      - opencv-python-headless==4.11.0.86
      - jupyterlab>=4,<5
